version: "3.8"

services:
  db:
    container_name: snap_db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./resources/sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snap_db
